name: Docker Image CI

on:
  push:
    branches: [ "gitaction" ]

jobs:
  build_docker_image:
    strategy:
      matrix:
        os: [ windows-2022, windows-2019 ]
        repo: [ mcr.microsoft.com/windows/servercore, mcr.microsoft.com/dotnet/framework/sdk ]
        node_version: [ current, lts, maintenance]
        include:
          - tag: ltsc2022
            os: windows-2022
            repo: mcr.microsoft.com/windows/servercore
          - tag: 4.8-windowsservercore-ltsc2022
            os: windows-2022
            repo: mcr.microsoft.com/dotnet/framework/sdk
          - tag: ltsc2019
            os: windows-2019
            repo: mcr.microsoft.com/windows/servercore
          - tag: 4.8-windowsservercore-ltsc2019
            os: windows-2019
            repo: mcr.microsoft.com/dotnet/framework/sdk
    runs-on: ${{ matrix.os }}
    steps:
      - name: State build target
        run: >
          Write-Host "Build node-windows, base image ${{ matrix.repo }}:${{ matrix.tag }}, node.js: ${{ matrix.node_version }}"
      - name: Get Node.js release schedule
        run: >
          Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/nodejs/Release/main/schedule.json' -UseBasicParsing -OutFile schedule.json
      - name: Get Node.js release list
        run: >
          Invoke-WebRequest -Uri 'https://nodejs.org/download/release/index.json' -UseBasicParsing -OutFile index.json
      - name: Build and tag Docker images
        run: >
          .\Build.ps1
        env:
          BASE_IMAGE_NAME: matrix.repo
          BASE_IMAGE_TAG: matrix.tag
          NODE_VERSION: matrix.node_version
      