name: Docker Image CI/CD

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: '15 3 * * *'
  workflow_dispatch:
    inputs:
      force_build:
        description: Force build job to run
        type: boolean
        default: false
        required: false
      publish_image:
        description: Publish images to Docker Hub
        type: boolean
        default: true
        required: false

env:
  REPO_NAME: 'node-windows'
  DOCKER_HUB_USERNAME: 'dsakura207'

jobs:
  update_release:
    name: Update Node.js releases
    runs-on: ubuntu-latest
    outputs:
      DO_BUILD: ${{ steps.update_release.outputs.DO_BUILD }}
    steps:
      - uses: actions/checkout@v3
      - name: Update Node.js release schedule and version list
        id: update_release
        shell: pwsh
        env:
          NODE_RELEASE_SCHEDULE: https://raw.githubusercontent.com/nodejs/Release/main/schedule.json
          NODE_RELEASE_VERSION: https://nodejs.org/download/release/index.json
        run: |
          ./UpdateRelease.ps1
  build_and_publish:
    needs: update_release
    if: ${{ needs.update_release.outputs.DO_BUILD || inputs.force_build }}
    name: Build and publish node-windows image
    strategy:
      max-parallel: 3
      matrix:
        os: [ windows-2022, windows-2019 ]
        repo: [ mcr.microsoft.com/windows/servercore, mcr.microsoft.com/dotnet/framework/sdk ]
        node_version: [ current, lts, maintenance]
        include:
          - tag: ltsc2022
            os: windows-2022
            repo: mcr.microsoft.com/windows/servercore
          - tag: 4.8-windowsservercore-ltsc2022
            os: windows-2022
            repo: mcr.microsoft.com/dotnet/framework/sdk
          - tag: ltsc2019
            os: windows-2019
            repo: mcr.microsoft.com/windows/servercore
          - tag: 4.8-windowsservercore-ltsc2019
            os: windows-2019
            repo: mcr.microsoft.com/dotnet/framework/sdk
    runs-on: ${{ matrix.os }}
    env:
      BASE_IMAGE_NAME: ${{matrix.repo}}
      BASE_IMAGE_TAG: ${{matrix.tag}}
      NODE_VERSION: ${{matrix.node_version}}
    steps:
      # ref is necessary to pull down latest commit, not the commit triggered workflow.
      - uses: actions/checkout@v3
        id: checkout_repo
        with:
          ref: ${{ github.ref }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and tag Docker images
        id: build_image
        run: |
          .\Build.ps1
      - name: Publish image tags to Docker Hub
        id: publish_image
        if: ${{ steps.build_image.outputs.DO_PUBLISH }}
        run: |
          docker.exe image push --all-tags $env:DOCKER_HUB_USERNAME/$env:REPO_NAME
      
